// Secondary_School/Biology/apps/cell-cycle-mitosis/src/App.vue
<template>
  <div class="min-h-screen bg-gray-900 text-white p-4 md:p-8">
    <header class="max-w-7xl mx-auto mb-8 flex items-center justify-between">
      <div>
        <h1 class="text-3xl md:text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-green-400">
          The Cell Cycle & Mitosis
        </h1>
        <p class="text-gray-400 mt-2">Interactive Visualizer for HKDSE Biology</p>
      </div>
      <!-- Progress Bar -->
      <div class="hidden md:block w-1/3">
         <div class="w-full bg-gray-700 rounded-full h-2.5">
            <div class="bg-blue-600 h-2.5 rounded-full transition-all duration-500" :style="{ width: (store.progress * 100) + '%' }"></div>
         </div>
      </div>
    </header>

    <main class="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-3 gap-8">
      <!-- Main Visualizer Area (2/3 width) -->
      <div class="lg:col-span-2 space-y-6">
        <CellVisualizer />
        <DnaGraph />
      </div>

      <!-- Sidebar Area (1/3 width) -->
      <div class="lg:col-span-1">
        <Dashboard />
      </div>
    </main>

    <footer class="mt-12 text-center text-white/40 text-sm z-10 p-4">
      <p class="italic mb-1">But God made the earth by his power; he founded the world by his wisdom and stretched out the heavens by his understanding. Jeremiah 10:12</p>
      <p class="text-xs mb-1 mt-2">「耶和華用能力創造大地，用智慧建立世界，用聰明鋪張穹蒼。」 耶利米書 10:12</p>
      <p class="text-xs mt-2 pt-2 border-t border-white/10">@ 2025 Generated by Gemini 3.0 Prepared by SF Lau</p>
    </footer>
    <div class="fixed bottom-2 right-2 text-[10px] text-white/20 pointer-events-none z-50">
      Visits: {{ visits }}
    </div>
  </div>
</template>

<script setup>
import CellVisualizer from './components/CellVisualizer.vue'
import Dashboard from './components/Dashboard.vue'
import DnaGraph from './components/DnaGraph.vue'
import { useMitosisStore } from './stores/mitosis'
import { ref, onMounted } from 'vue'

const store = useMitosisStore()
const visits = ref(0) // Default 0

onMounted(() => {
    const key = window.location.pathname.replace(/\//g, '_') || 'home';
    fetch(`https://api.countapi.xyz/hit/keithsflau-profile/${key}`)
      .then(res => res.json())
      .then(data => visits.value = data.value)
      .catch(err => console.error(err));
});
</script>

<style>
/* Global scrollbar styling */
::-webkit-scrollbar {
  width: 8px;
}
::-webkit-scrollbar-track {
  background: #1f2937; 
}
::-webkit-scrollbar-thumb {
  background: #4b5563; 
  border-radius: 4px;
}
::-webkit-scrollbar-thumb:hover {
  background: #6b7280; 
}
</style>

// Secondary_School/Biology/apps/cellular-respiration/src/App.jsx
import React, { useState, useEffect } from 'react';
import Dashboard from './components/Dashboard';
import Cytoplasm from './components/Cytoplasm';
import MitochondrialMatrix from './components/MitochondrialMatrix';
import InnerMembrane from './components/InnerMembrane';
import AnaerobicPathways from './components/AnaerobicPathways';
import Summary from './components/Summary';
import { Play, ArrowRight } from 'lucide-react';
import { motion } from 'framer-motion';

function App() {
  const [atp, setAtp] = useState(0);
  const [oxygen, setOxygen] = useState(true);
  const [organism, setOrganism] = useState('HUMAN'); // 'HUMAN' or 'YEAST'
  const [stage, setStage] = useState('IDLE'); // IDLE, SCROLL_START, GLYCOLYSIS, MATRIX, ETC, ANAEROBIC, FINISHED

  const startSimulation = () => {
    setAtp(0);
    setStage('GLYCOLYSIS');
  };

  const reset = () => {
    setAtp(0);
    setStage('IDLE');
  };

  // Helper to add ATP with visual feedback
  const addAtp = (amount) => {
    setAtp(prev => prev + amount);
  };

  // State Transitions
  const handleGlycolysisComplete = () => {
    addAtp(2);
    // Decision point based on Oxygen
    if (oxygen) {
       setStage('MATRIX');
    } else {
       setStage('ANAEROBIC');
    }
  };

  const handleMatrixComplete = () => {
     addAtp(2);
     setStage('ETC');
  };

  const handleMatrixFail = () => {
      // If Matrix fails due to no oxygen, we eventually fall back to anaerobic
      // But typically we show it stopping first.
      setStage('ANAEROBIC');
  };

  const handleEtcComplete = () => {
      addAtp(34); // Big payout
      setStage('FINISHED');
  };

  const handleEtcFail = () => {
     // If ETC fails (oxygen cut), chain backs up.
     // In a simple sim, we can direct to Anaerobic to show that pathway taking over for survival
     setStage('ANAEROBIC');
  };

  const handleAnaerobicComplete = () => {
      // No ATP added, but cycle done
      setStage('FINISHED');
  };

  // Watch for Oxygen toggles during critical stages to redirect flow dynamically
  useEffect(() => {
     if (stage === 'MATRIX' && !oxygen) {
        // Immediate feedback handled in component, but if it stays off, valid to switch?
        // Rely on component's onFail timer.
     }
     if (stage === 'ANAEROBIC' && oxygen) {
        // If oxygen comes back while fermenting, usually we finish fermentation then next glucose goes aerobic.
        // For this sim, we just finish the current anaerobic step.
     }
  }, [oxygen, stage]);

  return (
    <div className="min-h-screen bg-slate-900 pb-20 font-sans selection:bg-blue-500/30">
      <Dashboard 
        atp={atp} 
        oxygen={oxygen} 
        setOxygen={setOxygen}
        organism={organism}
        setOrganism={setOrganism}
        onReset={reset}
      />

      <main className="max-w-4xl mx-auto p-6 flex flex-col gap-6">
        
        {stage === 'IDLE' && (
           <div className="flex flex-col items-center justify-center min-h-[60vh] text-center gap-6">
              <motion.div 
                 initial={{ scale: 0.9, opacity: 0 }}
                 animate={{ scale: 1, opacity: 1 }}
                 className="p-8 bg-slate-800/50 rounded-3xl border border-slate-700/50 max-w-lg"
              >
                  <h2 className="text-3xl font-bold bg-gradient-to-r from-blue-400 to-emerald-400 bg-clip-text text-transparent mb-4">
                     Welcome to the Cell
                  </h2>
                  <p className="text-slate-400 mb-8 leading-relaxed">
                     Observe how cells convert Glucose into ATP energy. 
                     Toggle <strong>Oxygen</strong> to see the massive difference between Aerobic Respiration and Fermentation.
                  </p>
                  <button 
                    onClick={startSimulation}
                    className="group bg-blue-600 hover:bg-blue-500 text-white px-8 py-4 rounded-full font-bold text-xl flex items-center gap-3 transition-all hover:scale-105 active:scale-95 shadow-xl shadow-blue-900/20"
                  >
                     <Play className="fill-white" /> Start Simulation
                  </button>
              </motion.div>
           </div>
        )}

        {/* Stage 1: Cytoplasm */}
        {stage !== 'IDLE' && (
           <Cytoplasm 
              isActive={stage === 'GLYCOLYSIS'} 
              onComplete={handleGlycolysisComplete}
           />
        )}

        {/* Connector Arrow */}
        {stage !== 'IDLE' && stage !== 'GLYCOLYSIS' && (
            <div className="flex justify-center -my-2 relative z-10">
               <ArrowRight className="text-slate-600 rotate-90" size={32} />
            </div>
        )}

        {/* Aerobic Container */}
        {(stage === 'MATRIX' || stage === 'ETC' || (stage === 'FINISHED' && atp > 20)) && (
           <div className="space-y-6">
               <MitochondrialMatrix 
                  isActive={stage === 'MATRIX'} 
                  oxygen={oxygen}
                  onComplete={handleMatrixComplete}
                  onFail={handleMatrixFail}
               />
               
               {(stage === 'ETC' || stage === 'FINISHED') && (
                   <div className="flex justify-center -my-2 relative z-10">
                      <ArrowRight className="text-slate-600 rotate-90" size={32} />
                   </div>
               )}

               <InnerMembrane 
                  isActive={stage === 'ETC'}
                  oxygen={oxygen}
                  onComplete={handleEtcComplete}
                  onFail={handleEtcFail}
               />
           </div>
        )}

        {/* Anaerobic Container */}
        {(stage === 'ANAEROBIC' || (stage === 'FINISHED' && atp <= 4)) && (
           <AnaerobicPathways 
              isActive={stage === 'ANAEROBIC' || stage === 'FINISHED'}
              organism={organism}
              onComplete={handleAnaerobicComplete}
           />
        )}

      </main>

      {stage === 'FINISHED' && (
         <Summary 
            onRestart={startSimulation} 
            isAerobic={atp > 10} 
            totalAtp={atp}
         />
      )}</div></div>
  );
}



export default App;

const Footer = () => (
  <footer className="mt-12 text-center text-white/40 text-sm z-10 p-4">
      <p className="italic mb-1">But God made the earth by his power; he founded the world by his wisdom and stretched out the heavens by his understanding. Jeremiah 10:12</p>
      <p className="text-xs mb-1 mt-2">「耶和華用能力創造大地，用智慧建立世界，用聰明鋪張穹蒼。」 耶利米書 10:12</p>
      <p className="text-xs mt-2 pt-2 border-t border-white/10">@ 2025 Generated by Gemini 3.0 Prepared by SF Lau</p>
  </footer>
);

const VisitCounter = () => {
  const [visits, setVisits] = React.useState(0);
  React.useEffect(() => {
    const key = window.location.pathname.replace(/\//g, '_') || 'home';
    fetch(`https://api.countapi.xyz/hit/keithsflau-profile/${key}`)
      .then(res => res.json())
      .then(data => setVisits(data.value))
      .catch(err => console.error(err));
  }, []);
  return (
    <div className="fixed bottom-2 right-2 text-[10px] text-white/20 pointer-events-none z-50">
      Visits: {visits}
    
      <Footer />
      <VisitCounter />
    </div>
  );
};

export default App;
